// Temporary workaround very similar to https://github.com/deislabs/wasi-experimental-http.
// Once asynchronous functions, streams, and the upstream HTTP API are available, this should be removed.

// HTTP status code.
// This is currently an unsigned 16-bit integer,
// but it could be represented as an enum containing
// all possible HTTP status codes.
type status = u16

// HTTP URI of the current request.
type uri = string

// HTTP body.
// Currently, this is a synchronous byte array, but it should be
// possible to have a stream for both request and response bodies.
type body = list<u8>

// HTTP parameter queries, represented as a list of (name, value) pairs.
type params = list<tuple<string, string>>

// HTTP headers represented as a list of (name, value) pairs.
type headers = list<tuple<string, string>>

// HTTP method.
enum method {
    get,
    put,
    head,
    post,
    patch,
    delete,
    options,
}

// HTTP request.
record request {
    uri: uri,
    params: params,
    method: method,
    headers: headers,
    body: option<body>,
}

// HTTP response.
record response {
    status: status,
    body: option<body>,
    headers: option<headers>,
}

// HTTP errors returned by the runtime.
enum error {
    success,
    invalid-url,
    request-error,
    runtime-error,
    too-many-requests,
    destination-not-allowed,
}

// The entrypoint for an HTTP handler.
handle: func(req: request) -> response

// Send an HTTP request and return a response or a potential error.
send: func(req: request) -> expected<response, error>
